### ISSUE TITLE
Point system

### ISSUE THREAD

**Issue by Mohamed-A-Mohamed** [quizzard-edu/quizzard#141]
Add max and min numbers of points when creating and editing question. Also have numbers of points recieved upon answering a question depend on how many students have answered the question correctly (based on the equation Larry has in the design document).

**Comment by larryyueli** [comment]
In the question creation page, assign a default value to the max and min value so that the instructor doesn't have to enter them for every single question. We can use max=100 and min=10 as the default values. This could also be a setting in the global setting page.

**Comment by Mohamed-A-Mohamed** [comment]
Display roughly how many points a student can earn.
