### ISSUE TITLE
Cannot Utilize the Question Body Text editor in question Creation

### ISSUE THREAD

**Issue by mehtadarshan1** [quizzard-edu/quizzard#146]
I am assuming after the new materialize css got added in this might have gotten changed.
Main issue is Can't add picture/sites/videos:
![screen shot 2017-10-31 at 12 40 41 am](https://user-images.githubusercontent.com/24999877/32207761-7b3deb30-bdd4-11e7-81df-0610559ee5d2.png)

**Comment by ahmedqarmout2** [comment]
@mehtadarshan1 any ideas on why this broke?
