### ISSUE TITLE
Error message showing up after clicking on add new question.

### ISSUE THREAD

**Issue by larryyueli** [quizzard-edu/quizzard#153]
![image](https://user-images.githubusercontent.com/3384353/32286046-9d4198d8-bf02-11e7-89aa-90a6addbe8ab.png)

**Comment by ahmedqarmout2** [comment]
you need to run datagen. I made a lot of changes to the databases schema so you will need to run datagen. After you run datagen, you need to restart nodejs server. Let me know if that fixes the issue.

**Comment by larryyueli** [comment]
I did do datagen and restarted the server. It's the develop branch right?

**Comment by larryyueli** [comment]
Here is the error message.

![image](https://user-images.githubusercontent.com/3384353/32296365-76a407ae-bf22-11e7-8546-3f683a956cbe.png)

**Comment by ahmedqarmout2** [comment]
Cool. I have a fix ready for this. Will push it tonigjt

**Comment by ahmedqarmout2** [comment]
This is also due to another backend change to allow using text IDs instead of numbers

**Comment by mehtadarshan1** [comment]
on line 789 of server -> the function should call getAllQuestionsList, that was the problem
