### ISSUE TITLE
General settings page for admins 

### ISSUE THREAD

**Issue by esteeroramy** [quizzard-edu/quizzard#170]
Please comment with any settings you wish to be included in this page

**Comment by mehtadarshan1** [comment]
1. Waiting time for failed attempt
2.  Use OAUTH User authentication or MongoDB user authentication
3. Allow Discussion board to be open to all students or only to students who answered a question

**Comment by Mohamed-A-Mohamed** [comment]
4. Let Instructor choose how many people show on the leaderboard (right now it shows everyone in the class)
