### ISSUE TITLE
Question Deletion

### ISSUE THREAD

**Issue by mehtadarshan1** [quizzard-edu/quizzard#173]
We should start to think how we should implement the deletion of a question.

**Comment by ahmedqarmout2** [comment]
We won't be deleting the question, instead we will deactivate them just like how we did users. Except you won't be able to recover deleted questions(disabled forever)

**Comment by mehtadarshan1** [comment]
sounds good

**Comment by mehtadarshan1** [comment]
@ahmedqarmout2  You still need to remove questions stats from those users who answered, its not just about deactivating the question.

This means remove points/attemps/score anything related that affects students score.
