### ISSUE TITLE
Font In success modal should match Quizzard theme

### ISSUE THREAD

**Issue by mehtadarshan1** [quizzard-edu/quizzard#174]
![image](https://user-images.githubusercontent.com/24999877/32626098-58f37b00-c55c-11e7-9c77-6d63fedd76f6.png)

**Comment by esteeroramy** [comment]
@Mohammed-JS-Khan would you be able to look at this since you worked with this modal?

**Comment by Mohammed-JS-Khan** [comment]
I'll take a look.

**Comment by Mohammed-JS-Khan** [comment]
Not sure why its like that for you @mehtadarshan1 , this is what it looks like in the most recent develop:
![image](https://user-images.githubusercontent.com/9061203/32765799-262675b6-c8da-11e7-985b-061d7612bc68.png)

**Comment by Mohammed-JS-Khan** [comment]
I can leave the above font (which was the SWAL original font "open sans") or I can change it to match the rest of the app, which doesnt look as nice in my opinion:
![image](https://user-images.githubusercontent.com/9061203/32766045-28fc3130-c8db-11e7-9637-87ce2959bf49.png)
