### ISSUE TITLE
students can access /accountform, and able to create students

### ISSUE THREAD

**Issue by esteeroramy** [quizzard-edu/quizzard#197]

**Comment by esteeroramy** [comment]
students can create questions

**Comment by esteeroramy** [comment]
permission for edit question

**Comment by mehtadarshan1** [comment]
students can also access  this api call /answerForm , please block them

**Comment by mehtadarshan1** [comment]
students can create other students 
api call is /useradd, please block students

**Comment by mehtadarshan1** [comment]
api call /questiondel need to add permissions to it

**Comment by ahmedqarmout2** [comment]
fixed all the above
