### ISSUE TITLE
Bugs to be fixed 

### ISSUE THREAD

**Issue by esteeroramy** [quizzard-edu/quizzard#201]
## Done
1. [Done] log has some "error: [object object]" from when people do logger.log(err)
1. [Done]analytics make sure that the numbers don't go out of the cards
1. [Done] make sure everything looks good on mobile
1. [Done] Add an option to leaderboard settings to show all students and make it default (dont forget to set it to default when we use the reset to default functionality)
1. [Done] Proper formatting of the buttons in the admin view
1. [Done] fix admin view in general
1. [Done] Analytics show class analytics first.
1. [Done] Don't collapse replies by default (maybe if it has x replies)
1. [Done] cannot like or dislike replies, after first reply
1. [Done] Less space in discussion board (less white space)
1. [Done]Import/export button goes on top of navbar (fix z-index)
1. [Done] In analytics page of Admin view students names still show undefined
1. [Done] Better elegant default profile picture
1. [Done] if you hit enter on in analytics instructor, select top student in list
1. [Done] add 'X' in analytics
1. [Done] Discussion board alerts that discussion board is not available if it's turned off in settings....
1. [Done] updating first and last names doesn't work
1. [Done] in discussion board, if a string is too long it goes out of scope of the box
1. [Done] Change the `point/attempt` to `points per attempt`
1. [Done] in statistics, first answer is the id not userid
1. [Done] Add a default error in case anything happens
1. [Done] when in question view, id of the student is there, rather than userid
1. [Done] Fix names on top of all files
1. [Done]Remove the materialize CSS from summernote
1. [Done]in statistics, student default accuracy is 0% but when answers something wrong, accuracy is 0.00%
1. [Done] Matching question fix answer box expanding in creation and edit
1. [Done] in statistics, sort tables dynamically
1. [Done] Split navbar on mobile to have right and left sections
1. [Done] Add icons to mobile navbar
1. [Done] Move hint into incorrect modal.
1. [Done] in Question Ordering, if a string is too long it goes out of scope of the box - check other question types.
1. [Done] Change the prompts in feedback: `Feedback for the course instructor, feedback for the developers of quizzard`.
1. [Done] Fix the visibility snackbar colour.
1. [Done] add the name of the user in leaderboard under their picture in the podium
1. [Done] add where the user is in the main leaderboard like we have in the mini leaderboard
1. [Done] add ... in the leaderboard to show that the user is lower than the other student in the leaderboard?
1. [Done] Make sure leaderboard doesn't break when u want to display more people than in your class, and have a minimum of 3.
1. [Done] UI for sort by button, change button to be as longs as switch.
1. [Done] Change fire to be bigger and darker (darker than navbar).
1. [Done] Add leedabod titles to leedabod
1. [Done] Make first place look more special in leedabod
1. [Done] Center the eyes
1. [Done] Fix validation if min points is greater than max points - in Question edit and global settings
1. [Done] The message that will be displayed to the user after they successfully answer a question does not display, nor does it get saved, remove.
1. [Done] Added and editting question error messages.
1. [Done] Make the visibility/checkmarks stay when the page is changed
#### NoGo (means that we decided that we do not want to implement this feature/fix this bug)
1. [NoGo] Change location of snackbar to be the center rather than the right side?

Please add any more that you find to this, we can split them up once bug fix week starts.

**Comment by mehtadarshan** [comment]
The message that will be displayed to the user after they successfully answer a question does not display, nor does it get saved

**Comment by mehtadarshan1** [comment]
in Question Ordering, if a string is too long it goes out of scope of the box

**Comment by mehtadarshan1** [comment]
In analytics page of Admin view students names still show undefined

**Comment by mehtadarshan1** [comment]
Better elegant default profile picture

**Comment by esteeroramy** [comment]
* if you hit enter on in analytics instructor, select top student in list
* add 'X' in analytics

**Comment by esteeroramy** [comment]
in settings, sort tables dynamically

**Comment by esteeroramy** [comment]
when getting a question wrong, the hint shows up then disappears right away, then we get the timer. we need a better way to show the hint

**Comment by esteeroramy** [comment]
Discussion board alerts that discussion board is not available if it's turned off in settings....
