### ISSUE TITLE
Disable the student from answering multiple choice questions after they submit their answers

### ISSUE THREAD

**Issue by ahmedqarmout2** [quizzard-edu/quizzard#40]
Right now the student can still submit another answer even if they already answered the question. We should disable the answers.

**Comment by mehtadarshan1** [comment]
@ahmedqarmout2 Lets let the students answer again, so that they can study from it if they wanted to. In the backend we can just stop adding the points for that question

**Comment by larryyueli** [comment]
Agree with allowing them to answer again.
