### ISSUE TITLE
Points for student don't update on screen after answering question correctly

### ISSUE THREAD

**Issue by mehtadarshan1** [quizzard-edu/quizzard#46]
Right now i have to log out and log back in for the score to be updated on screen

**Comment by ahmedqarmout2** [comment]
Ayy nice catch. I noticed this last night, but I forgot to open an issue. Thank you for reminding me. After some investigation, I found the root of the issue. The points displayed are taken from the current session, when you logout and login again, the session gets refreshed, and with it the points. I will have a fix for that soon. Nice catch

**Comment by ahmedqarmout2** [comment]
fixed, will be in the next merge
