### ISSUE TITLE
Log In page should be fixed (not scrollable)

### ISSUE THREAD

**Issue by mehtadarshan1** [quizzard-edu/quizzard#56]
![image](https://user-images.githubusercontent.com/24999877/31458158-26f59588-ae8d-11e7-9f76-67cb9516afdb.png)

Have to scroll down to log in... not convenient

**Comment by ahmedqarmout2** [comment]
I will fix this as part of the design update

**Comment by ahmedqarmout2** [comment]
This won't be included in the current PR. It seems more complicated that I expected

**Comment by ahmedqarmout2** [comment]
@Mohamed-A-Mohamed  plz look into this while designing the new logo

**Comment by Mohamed-A-Mohamed** [comment]
Looked into this and it looks like the logo is too big :laughing: I reduced the width and height of the logo in login.css and that stops the scrolling. @ahmedqarmout2 You mentioned that it looked more complicated, would you let me know what you found out when you looked into this. Just incase I'm missing something.
