### ISSUE TITLE
Cannot add pictures greater than 200x200pixels 

### ISSUE THREAD

**Issue by mehtadarshan1** [quizzard-edu/quizzard#58]
![image](https://user-images.githubusercontent.com/24999877/31464723-3343525e-aea0-11e7-8745-630c04be7c39.png)

Tried to add a 122kb picture, and didn't get added.

**Comment by Mohamed-A-Mohamed** [comment]
Where did you try to add it? In the DB?

**Comment by ahmedqarmout2** [comment]
I will look into it

**Comment by mehtadarshan1** [comment]
No @Mohamed-A-Mohamed, I tried uploading a picture through creating a question process. didn't seem to work. and 200px X 200px is a very small picture
