### ISSUE TITLE
Once a user changes their password, the page doesn't reload or go elsewhere.

### ISSUE THREAD

**Issue by Mohammed-JS-Khan** [quizzard-edu/quizzard#59]
Momo found this bug while testing. Changing the password made no change to the page that was displayed for him. Ideally we think it should log the user out so they can log in an re-authenticate. Any thoughts? @larryyueli @ahmedqarmout2 @mehtadarshan1 @esteeroramy

**Comment by ahmedqarmout2** [comment]
After the password is changed, we should display a message. But we should not log them out, that does not make sense to me. I will do this as part of the new design update

**Comment by Mohammed-JS-Khan** [comment]
@ahmedqarmout2  They should be logged out in my opinion, cause you want them to have a new authentication "token". This will probably come in handy when we're security hardening the app later on.

**Comment by ahmedqarmout2** [comment]
The security is not handled by the backend based on cookies or password, that is after login, its handled by sessions. If the user changes the password, that wont affect the session in the backend. I understand your point, but it feels weird.

**Comment by ahmedqarmout2** [comment]
Will be implementing profile page instead
