### ISSUE TITLE
Entering Wrong Password Should Clear Password Field

### ISSUE THREAD

**Issue by Mohamed-A-Mohamed** [quizzard-edu/quizzard#62]
When you enter the wrong password, the password field should get cleared. Right now you have to manually clear the password field.

**Comment by Mohamed-A-Mohamed** [comment]
@larryyueli @ahmedqarmout2 @mehtadarshan1 @esteeroramy 

Hi everyone,

There are two ways @Mohammed-JS-Khan and I thought about doing this. One way is to clear the password field upon entering an incorect password, as we intended in the begining. The second is to instead highlight the data in the password field. This way if the user knows where to correct their password they have the ablility to edit the data instead of having to re-write the whole password. Which option do you think should be used?

**Comment by larryyueli** [comment]
I think the first way makes more sense, i.e., clear and password and focus on it for re-entering. In general, the password is not something that's supposed be incrementally edited.

**Comment by ahmedqarmout2** [comment]
I will take this since I am working on redoing the design elements

**Comment by ahmedqarmout2** [comment]
done, the fix will be merged soon

**Comment by Mohammed-JS-Khan** [comment]
@ahmedqarmout2 We already had this fix completed. We were waiting on your pull request to be merged before putting up this pull request to solve this issue as you suggested we do. Can we please be a little more transparent before we go ahead and reassign work as recently we've been doing double time for a lot of tasks.

**Comment by ahmedqarmout2** [comment]
My bad
