### ISSUE TITLE
If you have not answered any questions then Answered tab looks incorrect

### ISSUE THREAD

**Issue by esteeroramy** [quizzard-edu/quizzard#86]

**Comment by Mohammed-JS-Khan** [comment]
Here are some visuals:
![image](https://user-images.githubusercontent.com/9061203/31867759-88296536-b762-11e7-9e10-d9a1096328bb.png)
![image](https://user-images.githubusercontent.com/9061203/31867750-7194d490-b762-11e7-92e6-b266c4a09f2d.png)

**Comment by ahmedqarmout2** [comment]
I know, i was too lazy to fix that. But now I guess I have no choice
